name: Require Code Review Reminder

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize] # Se dispara en varios eventos de Pull Request

jobs:
  remind_review:
    runs-on: ubuntu-latest # Ejecuta en una m치quina virtual Ubuntu
    permissions:
      pull-requests: write # Necesita permisos para escribir en Pull Requests (comentarios)
    steps:
    - name: Post review reminder comment # Publica un comentario recordando la necesidad de revisi칩n
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          // Solo comentar si no hay ya comentarios del bot sobre revisi칩n o si no est치 aprobado
          if (pr.requested_reviewers.length === 0 && pr.review_comments === 0) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '游녦 춰Hola! Este Pull Request est치 listo para ser revisado. Por favor, aseg칰rate de que al menos un revisor del equipo lo apruebe antes de fusionarlo a la rama `main`.'
            });
          }